-- Faz 1 topluluk rozetleri (oturum 12+):
-- Yeni BadgeKey enum değerleri. Postgres ALTER TYPE ADD VALUE
-- idempotent değil; IF NOT EXISTS destekli (Postgres 12+, Neon OK).
ALTER TYPE "BadgeKey" ADD VALUE IF NOT EXISTS 'EXPERIENCED';
ALTER TYPE "BadgeKey" ADD VALUE IF NOT EXISTS 'PHOTOGRAPHER';
ALTER TYPE "BadgeKey" ADD VALUE IF NOT EXISTS 'CATEGORY_MASTER';
ALTER TYPE "BadgeKey" ADD VALUE IF NOT EXISTS 'EDITOR_CHOICE';
ALTER TYPE "BadgeKey" ADD VALUE IF NOT EXISTS 'WEEKLY_TOP_10';
ALTER TYPE "BadgeKey" ADD VALUE IF NOT EXISTS 'MONTHLY_TOP_10';
ALTER TYPE "BadgeKey" ADD VALUE IF NOT EXISTS 'ALL_TIME_TOP_50';
